FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ["Order.API/Order.API.csproj","Order.API/"]
COPY ["Shared.Contracts/Shared.Contracts.csproj","Shared.Contracts/"]

RUN dotnet restore "Order.API/Order.API.csproj"

COPY . .
WORKDIR "/src/Order.API"
RUN dotnet publish "Order.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet","Order.API.dll"]